### ISSUE TITLE
Provide a 'Show a => a -> Doc ann' function

### ISSUE THREAD

**Issue by ocharles** [quchen/show-prettyprint#3]
It's kind of odd that there's nothing that actually gives me the pretty-printed document :smile:

**Comment by quchen** [comment]
Are you using an older version maybe? Since 1.2 the package includes just that function, [viaShow](http://hackage.haskell.org/package/prettyprinter-1.2.0.1/docs/Data-Text-Prettyprint-Doc.html#v:viaShow).

**Comment by quchen** [comment]
Good point actually, that sounds like a useful addition.

**Comment by quchen** [comment]
Implemented and released as 0.2.2! Thanks for the suggestion.

https://hackage.haskell.org/package/show-prettyprint-0.2.2

**Comment by ocharles** [comment]
Yay, thank you! I'm going to go use this today :)
