### ISSUE TITLE
backslashes

### ISSUE THREAD

**Issue by reuleaux** [quchen/show-prettyprint#5]
it appears to me that backslashes are not handled correctly, for example
parsing some stuff, first _without_ `prettyPrint` (never mind the details,
just see that we have a `(Token "\\")`) there:
```
>>> snd $ nopos $ parse expr_ "\\x . f"
Node [Pair (Token "\\") (Ws ""),Node [Pair (Binder "x") (Ws " ")],Pair (Token ".") (Ws " "),Abstract ["x"] (Scope (Pair (Id (F (Id "f"))) (Ws "")))]
```
and now with `prettyPrint` I would expect proper indentation (yes, happy with that), and
`(Token "\\")` to be preserved, which is not the case however:
```
>>> prettyPrint $ snd $ nopos $ parse expr_ "\\x . f"
Node [Pair (Token "\") (Ws "")
     ,Node [Pair (Binder "x") (Ws " ")]
     ,Pair (Token ".") (Ws " ")
     ,Abstract ["x"] (Scope (Pair (Id (F (Id "f"))) (Ws "")))]
```
thanks,
-A

**Comment by quchen** [comment]
Fixed, thanks!
